trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'container_registry'
    repository: 'Nginx'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/nginx-folder'
    Contents: 'nginx.yaml'  # Adjusted to specifically target nginx.yaml
    TargetFolder: '$(Build.ArtifactStagingDirectory)/nginx-manifests'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/s'
    artifact: 'nginx-manifest'
    publishLocation: pipeline
