trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'container_registry'
    repository: 'Nginx'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
