trigger:
- main

pool:
  vmImage: ubuntu-latest

- task: Docker@2
  inputs:
    containerRegistry: 'container_registry'
    repository: 'Nginx'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
